apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels: # these labels are deployment labels
    app: payment
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: payment
      project: roboshop
      tier: db
  template:
    metadata:
      labels: # these labels are pod labels
        app: payment
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mysql
        image: mutthu2512/payment:h1
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: payment
        
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    app: payment
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port